### ISSUE TITLE
ISO20_DC_ChargeLoop Grammar Error

### ISSUE THREAD

**Issue by Mike-M0** [EVerest/cbexigen#71] opened 2024-02-22 12:06 UTC
in ISO-20-DC-ChargeLoop as well in Req as in Res, an en/decoding error occurs, when BPT_Dynamic_DC_CL is sent as option. It tries to encode a second option CLReqControlMode, which should not be there.
encoding:
![image](https://github.com/EVerest/cbexigen/assets/67682299/fd9600c6-f861-4cd8-9e1c-6c9116ae431f)
decoding:
![image](https://github.com/EVerest/cbexigen/assets/67682299/9184960b-9429-433c-b841-c56e63590aaf)

here the raw bytes of both Req and Res
[rawBytes.zip](https://github.com/EVerest/cbexigen/files/14373769/rawBytes.zip)

**Comment by SebaLukas** [comment] 2024-04-19 13:26
I'll take a look at how we can fix this in code generator. I have already been able to fix it manually in the generated c code.

**Comment by SebaLukas** [comment] 2024-04-29 07:12
The problem for AC and DC has already been solved for [libcbv2g](https://github.com/EVerest/libcbv2g/tree/bugfix/parameter-size-too-low-and-bpt-control-mode) in a separate branch. Here in cbexigen we still need some time to fix this.

**Comment by barsnick** [comment] 2024-10-23 13:19
For reference, here are the attached messages as hex streams (EXI part only):

DC_ChargeLoopReq:
```
80340474788aa7084b74580d0e0dffcb4b78403200b05904ae1f101021807c201fc2447409021d4600810ea300408551201fc3403c0fe0c807f0d00f03f87c1181fc028102141380207f0a09c0103f87b0981021d460040855120990000008b00028
```

DC_ChargeLoopRes:
```
803804478138395be5bbd0080deaeb7e0be840320063f0cb1701fc2047400010810987503e80001fc2209c0fe1209c0811977503e80001fc2209c0fa1d00e0
```

**Comment by barsnick** [comment] 2024-10-23 13:20
Closing as duplicate of https://github.com/EVerest/cbexigen/issues/52, further explanations and investigation will be done there.

**Comment by barsnick** [comment] 2024-10-23 13:21
Closing as duplicate of https://github.com/EVerest/cbexigen/issues/52, further investigation will be done there.

**Closed by barsnick** 2024-10-23 13:21 UTC
Labels: bug

**Comment by barsnick** [comment] 2024-11-18 11:11
I have created pull request https://github.com/EVerest/cbexigen/pull/89, and would appreciate if you could test this.
